"""Removed teachers and students id

Revision ID: 356607710834
Revises: 080613d0df32
Create Date: 2025-04-20 16:37:28.401939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356607710834'
down_revision: Union[str, None] = '080613d0df32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'id')
    op.drop_column('teachers', 'id')
    op.create_unique_constraint(op.f('uq_users_corporate_email'), 'users', ['corporate_email'])
    op.create_primary_key(op.f("pk_students"), "students", ["user_id"])
    op.create_primary_key(op.f("pk_teachers"), "teachers", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_corporate_email'), 'users', type_='unique')
    op.add_column('teachers', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('students', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint("pk_students", "students")
    op.drop_constraint("pk_teachers", "teachers")
    # ### end Alembic commands ###
