"""Added is_admin

Revision ID: c47356e1559b
Revises: 97354f80d827
Create Date: 2025-05-07 22:45:27.820730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47356e1559b'
down_revision: Union[str, None] = '97354f80d827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_students_user_id'), 'students', ['user_id'])
    op.create_unique_constraint(op.f('uq_teachers_user_id'), 'teachers', ['user_id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(op.f('uq_teachers_user_id'), 'teachers', type_='unique')
    op.drop_constraint(op.f('uq_students_user_id'), 'students', type_='unique')
    # ### end Alembic commands ###
