"""attendances is_expired

Revision ID: dea4d3916449
Revises: 4b3c82275299
Create Date: 2025-05-17 20:16:16.857375

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dea4d3916449"
down_revision: Union[str, None] = "4b3c82275299"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendances",
        sa.Column(
            "is_expired", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "extra_attendances",
        sa.Column(
            "is_expired", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("extra_attendances", "is_expired")
    op.drop_column("attendances", "is_expired")
    # ### end Alembic commands ###
