"""initial models

Revision ID: f3498ae4c7a8
Revises: d1a3e19d8dcb
Create Date: 2025-04-12 13:25:40.331979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3498ae4c7a8'
down_revision: Union[str, None] = 'd1a3e19d8dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday_enum').create(op.get_bind())
    op.create_table('sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('time_start_in_minutes_since_midnight', sa.Integer(), nullable=False),
    sa.Column('time_end_in_minutes_since_midnight', sa.Integer(), nullable=False),
    sa.Column('weekday', postgresql.ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday_enum', create_type=False), nullable=False),
    sa.CheckConstraint('time_end_in_minutes_since_midnight > time_start_in_minutes_since_midnight', name='check_time_end_after_start'),
    sa.CheckConstraint('time_end_in_minutes_since_midnight BETWEEN 0 AND 1439', name='check_valid_end_time'),
    sa.CheckConstraint('time_start_in_minutes_since_midnight BETWEEN 0 AND 1439', name='check_valid_start_time'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_section',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'section_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_section')
    op.drop_table('schedule')
    op.drop_table('sections')
    sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday_enum').drop(op.get_bind())
    # ### end Alembic commands ###
